-- Create case_suggested_forms table
CREATE TABLE IF NOT EXISTS public.case_suggested_forms (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id UUID NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  form_type TEXT,
  payer TEXT,
  state TEXT,
  confidence TEXT CHECK (confidence IN ('high', 'medium', 'low')),
  download_url TEXT,
  is_external BOOLEAN DEFAULT false,
  source_urls JSONB DEFAULT '[]',
  source_snippets JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster lookups by case_id
CREATE INDEX IF NOT EXISTS idx_case_suggested_forms_case_id ON public.case_suggested_forms(case_id);

-- Enable Row Level Security
ALTER TABLE public.case_suggested_forms ENABLE ROW LEVEL SECURITY;

-- Create policies for case_suggested_forms
-- Users can view forms for their own cases (via case_id -> user_id check)
CREATE POLICY "Users can view suggested forms for own cases"
  ON public.case_suggested_forms FOR SELECT
  USING (
    EXISTS (
        SELECT 1 FROM public.cases
        WHERE cases.id = case_suggested_forms.case_id
        AND cases.user_id = auth.uid()
    )
  );

-- Users can insert forms for own cases (technically server-side, but good for completeness if using service role, though RLS applies to auth users)
-- Usually generated by server, but if we want to allow RLS to pass:
CREATE POLICY "Users can insert suggested forms for own cases"
  ON public.case_suggested_forms FOR INSERT
  WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.cases
        WHERE cases.id = case_suggested_forms.case_id
        AND cases.user_id = auth.uid()
    )
  );

-- Users can delete forms for own cases
CREATE POLICY "Users can delete suggested forms for own cases"
  ON public.case_suggested_forms FOR DELETE
  USING (
    EXISTS (
        SELECT 1 FROM public.cases
        WHERE cases.id = case_suggested_forms.case_id
        AND cases.user_id = auth.uid()
    )
  );
